// Type definitions for dom-chef JSX

// Generated by AI while trying to get React and dom-chef to work in the same project.
declare global {
  namespace JSX {
    type Element = HTMLElement | null;
    type ElementChildrenAttribute = {
      children?: any;
    };
    type IntrinsicElements = {
      [K in keyof HTMLElementTagNameMap]: Partial<{
        [P in keyof HTMLElementTagNameMap[K]]: any;
      }> & {
        style?: any;
        children?: any;
        onClick?: ((e: Event) => void) | null;
        onChange?: ((e: Event) => void) | null;
        onInput?: ((e: Event) => void) | null;
        [key: string]: any;
      };
    } & {
      [elemName: string]: {
        [key: string]: any;
      };
    };
  }
}

declare module 'dom-chef' {
  export function h(
    tag: string | Function,
    props?: Record<string, any> | null,
    ...children: any[]
  ): HTMLElement;
}

// Make HTMLElement compatible with React.ReactNode when using dom-chef pragma
declare global {
  interface HTMLElement {
    $$typeof?: any;
  }
}

export {};
